Support migrate from an existing server
thijsvanloef/palworld-server-docker pull request #114
Opened 2024-01-25 20:11 UTC by Ericwww

## Context 

To solve #96 

I think `/palworld/Pal/Saved/Config/LinuxServer/GameUserSettings.ini` is generated after the service is started for the first time, so I can only write an additional script to facilitate migration.

After several experiments, the migration plan was determined to be successful.

## Test instructions

This script is also tested.

<img width="1245" alt="image" src="https://github.com/thijsvanloef/palworld-server-docker/assets/24605603/d6eb54b1-715a-49fd-ad52-eea880ee123e">

<img width="877" alt="image" src="https://github.com/thijsvanloef/palworld-server-docker/assets/24605603/2da6bd7e-d5f9-4754-80d8-50e5ab79e8fb">

<img width="784" alt="image" src="https://github.com/thijsvanloef/palworld-server-docker/assets/24605603/8b5a71d2-32d8-4719-87ab-168fb4c9c47f">

## Checklist before requesting a review

* [x] I have performed a self-review of my code
* [x] I've added documentation about this change to the README.
* [x] I've not introduced breaking changes.

2024-01-25 20:20 UTC, thijsvanloef requested changes

2024-01-25 20:20 UTC, thijsvanloef commented on README.md
I prefer to have this in a seperate readme in the migration folder

2024-01-25 20:40 UTC, Ericwww commented on README.md
OK, separated it.

2024-01-26 09:16 UTC, thijsvanloef requested changes
Could you also possibly document the way to do it manually in the readme?

2024-01-26 10:09 UTC, merged

2024-01-27 15:07 UTC, RoryKirsi commented
Is any option to work with the Windows server migrate to Linux server? (lock steam_appid.txt)