Added description for server
thijsvanloef/palworld-server-docker pull request #122
Opened 2024-01-26 02:48 UTC by Dashboy1998

## Context 

* Add a description to the server

## Choices

* Implemented the same as the other settings

## Test instructions

1. Set a description in docker-compose
2. Start container 
3. Join game
4. Go to the options in game to see the description. For my testing I did `Hello World`.
![20240125214337_1](https://github.com/thijsvanloef/palworld-server-docker/assets/18587674/29f12645-27f8-4232-bd20-8248859b5009)

## Checklist before requesting a review

* [x] I have performed a self-review of my code
* [x] I've added documentation about this change to the README.
* [x] I've not introduced breaking changes.

2024-01-26 05:56 UTC, fryfrog commented
You should wait for https://github.com/thijsvanloef/palworld-server-docker/pull/124 to be merged, then update your changes to incorporate it. The current way does not support spaces in the server name and wouldn't in the description.

2024-01-26 06:21 UTC, Dashboy1998 commented
> You should wait for https://github.com/thijsvanloef/palworld-server-docker/pull/124 to be merged, then update your changes to incorporate it. The current way does not support spaces in the server name and wouldn't in the description.

I didn't have any issues with spaces in the server name or description as and that can be seen in the photo in the PR.

2024-01-26 17:18 UTC, thijsvanloef requested changes
I've just merged #124, if you are able to, please change the way -serverdescription gets added to the STARTCOMMAND.

2024-01-26 18:13 UTC, thijsvanloef commented
Needed to revert #124, your PR is still on my radar, but #124 has to be fixed first, sorry for the inconvenience.

2024-01-27 09:47 UTC, thijsvanloef commented
There was some fuckery going on with the revert, I believe I fixed it

2024-01-27 09:48 UTC, Dashboy1998 commented on docker-compose.yml
> +         # Enable the environment variables below if you have COMMUNITY=true
Oops I added this comment again.

2024-01-27 09:52 UTC, merged