modify deployment and chart for opionated deployment
thijsvanloef/palworld-server-docker pull request #141
Opened 2024-01-26 18:09 UTC by Mercwri

## Context 

It is relatively unsafe with the way Palworld handles it's server terminations to leave the default deployment setting of RollingUpdate. Switching to Recreate ensures the old pod is terminated and not writting to the volume while the new pod is starting.

## Choices

Opionated change is done in the suggested deployment yaml and the chart sets Recreate by default but leave it a configurable option.

## Test instructions

Deployed to my local cluster, valiadate that deployment still works and that it terminates the pod prior to scheduling the new pod.

## Checklist before requesting a review

* [X] I have performed a self-review of my code
* [  ] I've added documentation about this change to the README.
* [X] I've not introduced breaking changes.

2024-01-26 18:11 UTC, thijsvanloef commented
Hi @Mercwri Thanks for taking the time to create this PR, i've marked it "help wanted" as I am currently not able to test it myself

2024-01-27 01:56 UTC, Filipe-Souza requested changes
After moving the property OK
![Screenshot 2024-01-26 224618](https://github.com/thijsvanloef/palworld-server-docker/assets/5497281/64f3679d-c75d-4eff-95b9-454942767acb)

2024-01-27 01:56 UTC, Filipe-Souza commented on chart/templates/deployments.yaml
Move the strategy property up to spec:

```

  selector:
    matchLabels:
      app.kubernetes.io/component: "{{ .Release.Name }}-server"
  strategy:
    type: "{{ .Values.server.strategy }}"
  template:
    metadata:
      annotations:
 ```

2024-01-27 03:19 UTC, Mercwri commented on chart/templates/deployments.yaml
Good catch, just pushed the fix.

2024-01-28 05:31 UTC, Filipe-Souza approved these changes

2024-01-28 09:30 UTC, merged