Allow changing of all config trough ENV
thijsvanloef/palworld-server-docker pull request #175
Opened 2024-01-28 11:12 UTC by thijsvanloef

## Context 

Prevent people from having to change files in order to change game options

## Choices

Add environment variables for every option in the game

## Test instructions

Set custom options and see if the PalWorldSettings.ini gets changed

## Checklist before requesting a review

* [ ] I have performed a self-review of my code
* [ ] I've added documentation about this change to the README.
* [ ] I've not introduced breaking changes.

2024-01-28 11:12 UTC, thijsvanloef commented
Still need to document everything

2024-01-28 12:15 UTC, MSpreckels reviewed
Remove configmap of palworldsetting.ini else it will get overridden

2024-01-28 12:15 UTC, MSpreckels commented on scripts/start.sh
> +fi
duplicate

142-145

2024-01-28 12:27 UTC, MSpreckels requested changes
You should also remove the configmap reference from deployment

https://github.com/thijsvanloef/palworld-server-docker/blob/5b72e8d926fbfc4c785ef9076b74c02e659e1d56/k8s/deployment.yaml#L42

https://github.com/thijsvanloef/palworld-server-docker/blob/5b72e8d926fbfc4c785ef9076b74c02e659e1d56/k8s/deployment.yaml#L49

2024-01-28 12:27 UTC, MSpreckels commented on k8s/configmap.yaml
> -    NetServerMaxTickRate=60
IMO this didn't work in the first place. We should make a PR and put this in Engine.ini.

2024-01-28 12:31 UTC, thijsvanloef commented
@MSpreckels I think I got everything

2024-01-28 12:32 UTC, MSpreckels commented
Now we have some parameters that appended to the startcommand and some that are replaced in the file. Wouldn't i make sense to even it out and set everything possible in file?

2024-01-28 12:42 UTC, MSpreckels commented on README.md
> +| Variable                                  | Description                                                    | Default Value
how did PLAYER_STOMACH_DECREASE_RATE get up there in the header? :D

2024-01-28 12:42 UTC, MSpreckels commented on README.md
> +| NETSERVERMAXTICKRATE                      | Changes the TickRate of the server.                            | 120
Not used right now

2024-01-28 12:57 UTC, thijsvanloef commented
@MSpreckels I've only changed some appended variables to the PalWorldSettings.ini. Mainly ENV's that include texts, as spacing could cause some trouble with the ini file

2024-01-28 13:06 UTC, merged

2024-05-08 00:58 UTC, Paddy32810 commented
I change the ENV parameters through the stack editor, then I deploy

I want to add : 

BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=0.000000
DEATH_PENALTY=Item
PAL_EGG_DEFAULT_HATCHING_TIME=0.00100
![image](https://github.com/thijsvanloef/palworld-server-docker/assets/50557539/8abf8226-9a57-4fb4-beb6-8a5ca4a14979)


at the end, but it doesn't work. My eggs still take 36hours to hatch. How do I solve this ? Obviously changing Palwordsettings.ini doesn't work at all.