Fix RCON variable handling
thijsvanloef/palworld-server-docker pull request #233
Opened 2024-01-31 04:46 UTC by pipixi

## Context 

Fix RCON variable handling

## Choices

RCON setting in <code>PalWorldSettings.ini</code> 
not work:
<code>RCONEnabled=true</code>
correct: 
<code>RCONEnabled=True</code>

## Test instructions
docker run :
<pre>docker run -d \
    --name palworld-server \
    -p 8211:8211/udp \
    -p 27015:27015/udp \
    -v /data:/palworld/ \
    -e PUID=1000 \
    -e PGID=1000 \
    -e PORT=8211 \
    -e PLAYERS=16 \
    -e MULTITHREADING=true \
    -e RCON_ENABLED=true \
    -e RCON_PORT=25575 \
    -e TZ=UTC \
    -e ADMIN_PASSWORD=test \
    -e SERVER_NAME=Dog \
    -e SERVER_DESCRIPTION=20240131 \
    --restart unless-stopped \
    --stop-timeout 30 \
    --pull=always \
    thijsvanloef/palworld-server-docker:latest</pre>

verify:

run container:  <code>docker exec -it palworld-server rcon-cli info</code>

<pre>bb@bb-M1090:~/config$ docker  exec -it palworld-server rcon-cli info
Welcome to Pal Server[v0.1.3.0] Dog </pre>

## Checklist before requesting a review

* [x] I have performed a self-review of my code
* [x] I've added documentation about this change to the README.
* [x] I've not introduced breaking changes.

2024-01-31 06:07 UTC, llnut requested changes
I think `${RCON_ENABLED}` should be converted to lowercase before comparing it with `true`.

2024-01-31 06:54 UTC, pipixi commented on scripts/start.sh
> +    if [ "${RCON_ENABLED}" = true ]; then
Looks like a good suggestion :)

2024-01-31 08:45 UTC, thijsvanloef commented
The issue related to this has been marked closed by the author, I also cannot seem to recreate the issue relating to using a lowercase `true`. Is this PR still necessary?

2024-01-31 20:12 UTC, Dashboy1998 commented
I am unable to reproduce the issue that this is supposed to fix.

I have tried a mixture for the value
* true
* false
* TRue
* TruE
* truE
* FalsE

All seem to be accepted by the game.

2024-02-01 01:52 UTC, pipixi commented
> The issue related to this has been marked closed by the author, I also cannot seem to recreate the issue relating to using a lowercase `true`. Is this PR still necessary?

No need, This is a misunderstanding.

2024-02-01 01:52 UTC, closed without merging