feat: Publish to GHCR
thijsvanloef/palworld-server-docker pull request #353
Opened 2024-02-10 21:28 UTC by USA-RedDragon

## Context 

* Release the Docker images to the GitHub Container repository which is free and isn't subject to the same rate limiting as Docker Hub

## Choices

* I added jobs in parallel with the Docker Hub release jobs to push to GHCR
* I added a workflow to publish developer images to GHCR as well

## Test instructions

1. Just ran the workflows in my fork, resulting in: https://github.com/USA-RedDragon/palworld-server-docker/pkgs/container/palworld-server-docker

## Checklist before requesting a review

* [X] I have performed a self-review of my code
* [X] I've added documentation about this change to the README.
* [X] I've not introduced breaking changes.

2024-02-10 23:46 UTC, Twinki14 requested changes
Instead of brand new workflows, we should keep docker image publishing all in the same workflow

Ideally this would be building the image then pushing to both registries in the same workflow job

2024-02-11 00:25 UTC, USA-RedDragon commented
Question, are you referring to the extra workflow for the GHCR Development Builds? Or do you mean I should be pushing to both GHCR and Docker Hub in the same job in `release.yaml`? (Or both?)

2024-02-11 00:45 UTC, Twinki14 approved these changes
Perfect! Could not have done it better myself

2024-02-11 10:57 UTC, thijsvanloef approved these changes

2024-02-11 11:11 UTC, merged