added german language files
thijsvanloef/palworld-server-docker pull request #403
Opened 2024-02-17 19:11 UTC by tomxpcvx

## Context 

* This PR adds german language support for the docusaurus.

## Choices

* 

## Test instructions

1. Navigate to the docusaurus folder
2. Run: `npm start -- --locale de`

## Checklist before requesting a review

* [x] I have performed a self-review of my code
* [x] I've added documentation about this change to the README.
* [x] I've not introduced breaking changes.

2024-02-17 19:15 UTC, tomxpcvx commented
Hi Thijs,
is it also possible to translate the content from the Markdown files? 😄

2024-02-17 19:18 UTC, tomxpcvx commented
Hi :smile:
I just wanted to make it clear that I've started translating, not that several people are making the effort at the same time and can translate together instead.

2024-02-17 19:50 UTC, MSpreckels commented
you might want to mark it as draft if you dont want @thijsvanloef to merge it :)

2024-02-17 22:28 UTC, tomxpcvx commented
Hey guys 👋🏼
I squashed my commits into one commit, so that everything is easier to maintain 😄 

I also checked that everything looks good in docusaurus and checked the links pointing to headings hopefully work in production. I used the Dutch language files as a guide because it works there.

In the meantime there have been markdown lint checks. Unfortunately I can't see the current status.

If there is anything that needs to be fixed, please let me know. 😊

2024-02-18 09:28 UTC, MSpreckels requested changes
Hey there! I've skimmed over the translation and found a few things. IMO, it's an accurate translation which sometimes feels abit stiff.

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/advanced/kubernetes.md
> +Der offizielle Helm-Chart befindet sich in einem separaten Repository, [palworld-server-chart](https://github.com/Twinki14/palworld-server-chart)
Das offizielle Helm-Chart [...]

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/advanced/palworld-directory.md
> +| backups                      | Ordner, in dem alle Backups des Befehls `backup` gespeichert werden    |
Reicht es nicht zu sagen

"Der Ordner, in dem alle Backups gespeichert werden" ?

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/configuration/game-settings.md
> +Das Konvertieren von Servereinstellungen in Umgebungsvariablen folgt denselben Prinzipien (mit einigen Ausnahmen):
Das liest sich komisch. Vllt sowas wie:

"Um Servereinstellung in Umgebungsvariablen zu konvertieren müssen folgende Regeln eingehalten werden:"

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/configuration/game-settings.md
> +* den einzelnen Buchstaben entfernen, wenn die Einstellung damit beginnt (wie 'b')
"falls die Einstellung mit einem einzelnen Buchstaben beginnt, muss dieser entfernt werden (z.B. 'b')."

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/configuration/game-settings.md
> +| PAL_CAPTURE_RATE                          | Pal-Fangerate                                                  | 1.000000
Da ist ein 'e' zu viel oder nicht?
"Pal-Fangrate"

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/configuration/game-settings.md
> +| PAL_DAMAGE_RATE_DEFENSE                   | Schadensmultiplikator zu Pals                                 | 1.000000
"Verteidigungsmultiplikator von Pals"

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/configuration/game-settings.md
> +| PLAYER_DAMAGE_RATE_DEFENSE                | Schadensmultiplikator zu Spielern                              | 1.000000
Verteidigungsmultiplikator [...]

2024-02-18 09:28 UTC, MSpreckels commented on docusaurus/i18n/de/docusaurus-plugin-content-docs/current/getting-started/quick-setup.md
> +      stop_grace_period: 30s # Auf die Zeit festlegen, die Sie bereit sind zu warten, bis der Container ordnungsgemäß beendet ist
"die Zeit, die Sie bereit sind zu warten, bis der Container ordnungsgemäß beendet ist"

2024-02-18 17:56 UTC, tomxpcvx commented
Hi, I have added your suggestions. I also tried not to change too much of the meaning and form of the original texts. And in some places it was actually a bit stiff.

2024-02-18 18:55 UTC, merged